## YAML Template.
# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

    #group:
    #    group_class:   Application\Sonata\UserBundle\Entity\Group
    #    group_manager: sonata.user.orm.group_manager
 
    #service:
     #   user_manager: sonata.user.orm.user_manager
 
    #profile:
        # Authentication Form
    #    form:
    #        type:               fos_user_profile
    #        handler:            fos_user.profile.form.handler.default
    #        name:               fos_user_profile_form
    #        validation_groups:  [Authentication]
    #template:
    #    engine: twig
            
            
# FOS User Configuration
# OLD CONFIGURATION
#fos_user:
#    db_driver: orm
#    firewall_name: main
#    user_class: Application\Sonata\UserBundle\Entity\User
#    
#    group:
#        group_class: Application\Sonata\UserBundle\Entity\Group
#    
#    template:
#        engine: twig