
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:     %mailer_host%
    encryption: ssl
    auth_mode: login
    username: %mailer_user%
    password: %mailer_password%
    sender_address: %mailer_sender_address%
    disable_delivery: %mailer_disable%
  