login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

entity:
    resource: "@EntityBundle/Resources/config/routing.yml"
    prefix:   /entity

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
