parameters:
    comment.listeners.timestamp.class: Admin\CommentBundle\Listener\TimestampListener
    comment.form.class: Symfony\Component\Form\Form
    comment.form.type.class: Admin\CommentBundle\Form\Type\CommentFormType
    comment.form.handler.class: Admin\CommentBundle\Form\Handler\CommentFormHandler
    comment.model.class: Admin\CommentBundle\Entity\Comment
    comment.services.comment_helper_class: Admin\CommentBundle\Services\CommentHelper
    comment.services.controller_class: Admin\CommentBundle\Controller\DefaultController

services:
    admin_comment.timestamp_listener:
        class: %comment.listeners.timestamp.class%
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    admin_comment.services.controller:
        class: %comment.services.controller_class%
        scope: request
        arguments:
            - "@service_container"

    admin_comment.services.commenthelper:
        class: %comment.services.comment_helper_class%
        scope: request
        arguments:
            - "@doctrine.orm.entity_manager"

    admin_comment.comment.form:
        factory_method: createNamed
        factory_service: form.factory
        class: %comment.form.class%
        arguments:
            - commentform_form                      # name of the form
            - commentform                           # alias of the form type
            - null                                  # data to bind, this is where your entity could go if you have that defined as a service
            - { validation_groups: [AddComment] }   # validation groups

    admin_comment.comment.form.handler:
        class: %comment.form.handler.class%
        scope: request
        arguments:
            - "@admin_comment.comment.form"
            - "@request"
            - "@service_container"
            - "@doctrine.orm.entity_manager"

    admin_comment.comment.form.type:
        class: %comment.form.type.class%
        tags:
            - { name: form.type, alias: commentform }
        arguments:
            - %comment.model.class%
            - "@service_container"

