parameters:
    menu.services.helpers_class: Admin\MenuBundle\Services\Helpers

services:
    admin_menu.services.helpers:
        class: %menu.services.helpers_class%
        arguments: [""]

    admin_menu.menu_builder:
        class: Admin\MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager", "@service_container"]

    admin_menu.voter.request:
        class: Admin\MenuBundle\Voter\RequestVoter
        arguments: ["@service_container"]
        tags:
            - { name: knp_menu.voter }

    admin_menu.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: admin_menu.menu_builder
        factory_method: createMenu
        arguments: ["@request", "Main Menu","menu left","main"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    admin_menu.menu.footer:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: admin_menu.menu_builder
        factory_method: createMenu
        arguments: ["@request", "Footer Menu", "footer-menu menu inline-list center", "simple"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: footer } # The alias is what is used to retrieve the menu

    admin_menu.menu.mainsitemap:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: admin_menu.menu_builder
        factory_method: createMenu
        arguments: ["@request", "Main Menu", "sitemapList side-nav", "simple"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: mainsitemap } # The alias is what is used to retrieve the menu

    admin_menu.menu.footersitemap:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: admin_menu.menu_builder
        factory_method: createMenu
        arguments: ["@request", "Footer Menu", "sitemapList side-nav", "simple"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: footersitemap } # The alias is what is used to retrieve the menu
