parameters:
    skeleton.services.helpers_class: Admin\SkeletonBundle\Services\Helpers

services:
    admin_skeleton.services.helpers:
        class: %page.services.helpers_class%
        arguments: ["@doctrine.orm.entity_manager"]



